name: Generate Sponsors README

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Sponsors README
        uses: JamesIves/github-sponsors-readme-action@releases/v1-org
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          organization: true
          minimum: 5
