name: Sponsors

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update `Sponsors` section
        uses: JamesIves/github-sponsors-readme-action@releases/v1-org
        with:
          token: ${{ secrets.PAT }}
          file: 'README.md'
          organization: true
          minimum: 5
      - name: Commit changes
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: '.'
